import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainWrapper from "@/context/MainWrapper";
import { getServerSession } from "next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TEESTING PREV LOGIC",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // default favicon
  },
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased select-none `}
      >
        <MainWrapper session={session} >
          {children}
        </MainWrapper>
      </body>
    </html>
  );
}
